sudo: false
language: python
python:
  - 2.6
env:
  - FLASK_VERSION=0.12
install:
  - pip install -q Flask==$FLASK_VERSION
  - pip install -q -r requirements.txt
  - pip install -q -r dev-requirements.txt
script:
  - nosetests -vs tests --with-coverage --cover-package=app
after_success:
  - coveralls
